name: ie-bank-empty-retakers-rg

on:
  push:
    paths:
      - 'scripts/**' # Trigger only with changes under folder 'scripts'
  schedule:
    - cron: '59 21 * * *' # Trigger at 23:59 CEST (UTC + 2) every day
  workflow_dispatch: # Trigger manually

env:
  RESOURCE_GROUP_RETAKERS: BCSAI2024-DEVOPS-RETAKERS-DEV
  SUBSCRIPTION_ID_DEV: e0b9cada-61bc-4b5a-bd7a-52c606726b3b

jobs:
  remove-resource-groups:
    runs-on: ubuntu-latest
    steps:
    # Checkout code
    - uses: actions/checkout@main
    
    # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true

    # Empty resource group students retakers
    - name: empty-resource-group-retakers
      uses: azure/powershell@v1
      with:
          inlineScript: ./scripts/empty-resource-group -ResourceGroupName "${{ env.RESOURCE_GROUP_RETAKERS }}" -SubscriptionId "${{ env.SUBSCRIPTION_ID_DEV }} "
          azPSVersion: "latest"